logging:
  receivers:
    webapp-receiver:
      type: files
      include_paths:
        - /tmp/info.log
        - /tmp/error.log
      record_log_file_path: true
  processors:
    webapp-processor:
      type: parse_json
      time_key: time
      time_format: "%Y-%m-%dT%H:%M:%S.%L%Z"
  service:
    pipelines:
      default_pipeline:
        receivers: [webapp-receiver]
        processors: [webapp-processor]
