project_id = "yash-cloud"
provisioner_webapp_source = "/home/runner/work/webapp/webapp/webapp.zip"
provisioner_webapp_destination = "tmp/webapp.zip"
provisioner_service_source = "../webapp.service"
provisioner_service_destination = "tmp/webapp.service"