name: Image Build

on:
  pull_request:
    branches:
      - main

jobs:
  image-build:
    runs-on: ubuntu-latest

    env:
      DB_NAME: ${{ vars.DB_NAME }}
      DB_USERNAME: ${{ vars.DB_USERNAME }}
      DB_PASS: ${{ secrets.DB_PASS }}
      HOST: ${{ vars.HOST }}
      PORT: ${{ vars.PORT }}
      DIALECT: ${{ vars.DIALECT }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: "Create .env file"
      working-directory: ${{ github.workspace }}
      run: |
        touch .env
        echo HOST=${{ vars.HOST }} >> .env
        echo DB_NAME=${{ vars.DB_NAME }} >> .env
        echo DB_USER=${{ vars.DB_USERNAME }} >> .env
        echo DB_PASSWORD=${{ vars.DB_PASS }} >> .env
        echo PORT: ${{ vars.PORT }} >> .env
        echo DIALECT: ${{ vars.DIALECT }} >> .env
    
    - name: Build Artifacts
      working-directory: ${{ github.workspace }}
      run: zip -r webapp.zip .

    - name: Set up Google Cloud SDK
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

    - name: Run Packer
      run: | 
        cd packer/
        packer init gcp-centos.pkr.hcl
        packer fmt gcp-centos.pkr.hcl
        packer validate -var-file="variables.pkrvars.hcl" gcp-centos.pkr.hcl
        packer build --force -var-file="variables.pkrvars.hcl" gcp-centos.pkr.hcl
