name: Image Build

on:
  pull_request:
    branches:
      - main

jobs:
  image-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Build Artifacts
      working-directory: ${{ github.workspace }}
      run: zip -r webapp.zip .

    - name: Set up Google Cloud SDK
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

    # - name: Run Packer
    #   run: | 
    #     cd packer/
    #     packer init gcp-centos.pkr.hcl
    #     packer fmt .
    #     packer validate -var-file="variables.pkrvars.hcl" -var 'project_id=${{ secrets.PROJECT_ID }}'  -var 'sa_email=${{ secrets.SA_EMAIL }}' gcp-centos.pkr.hcl
    #     packer build --force -var-file="variables.pkrvars.hcl" -var 'project_id=${{ secrets.PROJECT_ID }}' -var 'sa_email=${{ secrets.SA_EMAIL }}' gcp-centos.pkr.hcl
