name: Image Build

on:
  pull_request:
    branches:
      - main

jobs:
  image-build:
    runs-on: ubuntu-latest

    env:
      DB_NAME: ${{ vars.DB_NAME }}
      DB_USERNAME: ${{ vars.DB_USERNAME }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_HOST: ${{ vars.DB_HOST }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: "Create .env file"
      run: |
        touch .env
        echo DB_HOST=localhost >> .env
        echo DB_NAME=${{ vars.DB_NAME }} >> .env
        echo DB_USER=${{ vars.DB_USERNAME }} >> .env
        echo DB_PASSWORD=${{ vars.DB_PASS }} >> .env
    
    - name: Build Artifact
      working-directory: ${{ github.workspace }}
      run: |
        zip -r webapp.zip .
        ls -l
    
    - name: Set up Google Cloud SDK
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

    - name: Run Packer
      run: | 
        cd packer/
        packer init gcp-centos.pkr.hcl
        packer fmt gcp-centos.pkr.hcl
        packer validate -var-file="variables.pkrvars.hcl" gcp-centos.pkr.hcl
        packer build --force gcp-centos.pkr.hcl
