name: Integration Test

on:
  pull_request:
    branches:
      - main

jobs:
  integration-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: ${{ vars.DB_NAME }}
          MYSQL_USER: ${{ vars.DB_USERNAME }}
          MYSQL_PASSWORD: ${{ secrets.DB_PASS }}

    steps:
      - uses: actions/checkout@v4

      - name: "Create .env file"
        run: |
          touch .env
          echo DB_HOST=localhost >> .env
          echo DB_NAME=${{ vars.DB_NAME }} >> .env
          echo DB_USER=${{ vars.DB_USERNAME }} >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASS }} >> .env
      
      - name: Checkout Repository
        uses: actions/checkout@v2
  
      - name: Install MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client
          echo "MySQL is installed!"
      
      - name: Start MySQL service
        run: |
          sudo service mysql start
          sleep 10
      
      - name: Setup DB User
        run: |
          sudo mysql -u root -p -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '${{secrets.DB_PASS}}';"
          sudo mysql -D ${{vars.DB_NAME}} -e "GRANT ALL PRIVILEGES ON ${{vars.DB_NAME}}.* TO 'root'@localhost;"
          sudo mysql -D ${{vars.DB_NAME}} -e "FLUSH PRIVILEGES;"
     
      - name: Create Database
        run: |
          mysql -h localhost -u root --password=${{ secrets.DB_PASS }} -e "CREATE DATABASE ${{ vars.DB_NAME }}"

      - name: Verify Database Creation
        run: |
          mysql -h localhost -u root --password=${{ secrets.DB_PASS }}  -e "SHOW DATABASES;"

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Run Integration Tests
        run: npm test
