name: Integration Test

on:
  pull_request:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-la ''test

    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: ${{ vars.DB_NAME }}
          MYSQL_USER: ${{ vars.DB_USER }}
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_ROOT_PASSWORD: root_password  # Change this as per your security requirements

    steps:
      - uses: actions/checkout@v4

      - name: "Create .env file"
        run: |
          touch .env
          echo DB_HOST=localhost >> .env
          echo DB_NAME=${{ vars.DB_NAME }} >> .env
          echo DB_USER=${{ vars.DB_USER }} >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
          echo DB_DIALECT=mysql >> .env

      - name: Install dependencies
        run: npm install

      - name: Install MySQL client
        run: npm install mysql2

      - name: Run tests
        run: npm run test
        env:
          MYSQL_HOST: localhost
          MYSQL_PORT: 3306
