name: Integration Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  integration-test:
    runs-on: ubuntu-latest

    env:
      DB_NAME: ${{ vars.DB_NAME }}
      DB_USERNAME: ${{ vars.DB_USERNAME }}
      DB_ROOT_PASS: ${{ secrets.DB_ROOT_PASS }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Start MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e "CREATE DATABASE IF NOT EXISTS $DB_NAME;" -u$DB_USERNAME -p$DB_ROOT_PASS
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: "Create .env file"
        run: |
          touch .env
          echo HOST=${{ vars.HOST }} >> .env
          echo DB_NAME=${{ vars.DB_NAME }} >> .env
          echo DB_USERNAME=${{ vars.DB_USERNAME }} >> .env
          echo DB_PASS=${{ secrets.DB_ROOT_PASS }} >> .env
          echo PORT=${{ vars.PORT }} >> .env
          echo DIALECT=${{ vars.DIALECT }} >> .env

      - name: Install Dependencies
        run: npm install
      
      - name: Run Integration Tests
        run: npm test
