name: Integration Test

on:
  pull_request:
    branches:
      - main

jobs:
  integration-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: ${{ vars.DB_NAME }}
          MYSQL_USER: ${{ vars.DB_USERNAME }}
          MYSQL_ROOT_PASSWORD: ${{ vars.DB_PASS }}

    steps:
      - uses: actions/checkout@v4

      - name: "Create .env file"
        run: |
          touch .env
          echo DB_HOST=localhost >> .env
          echo DB_NAME=${{ vars.DB_NAME }} >> .env
          echo DB_USER=${{ vars.DB_USERNAME }} >> .env
          echo DB_PASSWORD=${{ vars.DB_PASS }} >> .env
          echo "Environment Variables: ${{ toJson(env) }}"
          cat .env
      
      - name: Checkout Repository
        uses: actions/checkout@v2
  
      - name: Install MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client
          echo "MySQL is installed!"
      
      - name: Start MySQL service
        run: |
          sudo service mysql start
          sleep 10

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install
      
      - name: Set environment variables
        run: |
          export DB_HOST=localhost
          export DB_NAME=${{ vars.DB_NAME }}
          export DB_USER=${{ vars.DB_USERNAME }}
          export DB_PASSWORD=${{ vars.DB_PASS }}

      - name: Run Integration Tests
        run: npm test
