name: Integration Test

on:
  pull_request:
    branches:
      - main

jobs:
  integration-test:
    runs-on: ubuntu-latest

    env:
      DB_NAME: ${{ vars.DB_NAME }}
      DB_USERNAME: ${{ vars.DB_USERNAME }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_HOST: ${{ vars.DB_HOST }}

    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: ${{ vars.DB_NAME }}
          MYSQL_ROOT_PASSWORD: ${{ vars.DB_PASS }}
          MYSQL_ALLOW_EMPTY_PASSWORD: true
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: "Create .env file"
        run: |
          touch .env
          echo DB_HOST=localhost >> .env
          echo DB_NAME=${{ vars.DB_NAME }} >> .env
          echo DB_USER=${{ vars.DB_USERNAME }} >> .env
          echo DB_PASSWORD=${{ vars.DB_PASS }} >> .env
      
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install
      
      - name: Run Integration Tests
        run: npm test
