name: Validate Packer

on:
  pull_request:
    branches:
      - main

jobs:
  validate-packer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Build Artifacts
      working-directory: ${{ github.workspace }}
      run: zip -r webapp.zip .
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: application-artifacts
        path: /artifacts/

    - name: Packer fmt
      run: |
        pwd
        cd packer/
        packer init gcp-centos.pkr.hcl
        packer fmt -check gcp-centos.pkr.hcl
        if [ $? -ne 0 ]; then
          echo "Packer template formatting check failed."
          exit 1
        fi

    - name: Packer validate
      run: |
        pwd
        cd packer/
        packer validate -var-file="variables.pkrvars.hcl" gcp-centos.pkr.hcl
        if [ $? -ne 0 ]; then
          echo "Packer template validation failed."
          exit 1 
        fi